name: Static analysis
on: [push, pull_request]

jobs:
  Cpp:
    runs-on: ubuntu-22.04
    steps:
    - uses: actions/checkout@v2
    - name: Formatting
      uses: Flamefire/clang-format-lint-action@master
      with:
        source: src
        clangFormatVersion: 9

  Python:
    runs-on: ubuntu-22.04
    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-python@v4
      with:
        python-version: 3.8
    - name: Install Python packages
      run: |
        pip install --upgrade pip
        pip install --upgrade flake8
    - name: Run flake8
      run: flake8 benchmark scorep test
